modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="djinterview"
version="${file.jarVersion}"
displayName="Marbles"
logoFile="examplemod.png"
credits=""
authors="DarkGuardsman"
description='''
Sample mod created for DoubleJump interview
'''

[[dependencies.djinterview]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.djinterview]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
